from pathlib import Path
import re
p=Path('mm060/app/src/main/java/com/technicallyunavailable/malfunctionmarbles/GameRenderer.java')
s=p.read_text()
def R(a,b):
    global s
    if a not in s: raise SystemExit('missing pattern: '+a[:90])
    s=s.replace(a,b)
R('private final float[][] path=new float[POINTS][3];','private final float[][] path=new float[POINTS][3];\n    private final float[] cumulativeLength=new float[POINTS];\n    private float trackLength=1f;')
R('float progress,velocity,lane,laneVelocity,spin,air,airVelocity,funnelAngle;','float progress,velocity,lane,laneVelocity,spin,air,airVelocity,funnelAngle; // velocity = world units/second')
R('sphere=Mesh.sphere(22,16);','sphere=Mesh.sphere(30,22);')
R('''        for(int i=POINTS-10;i<POINTS;i++)path[i][1]=path[POINTS-10][1]-(i-(POINTS-10))*.12f;\n    }''','''        for(int i=POINTS-10;i<POINTS;i++)path[i][1]=path[POINTS-10][1]-(i-(POINTS-10))*.12f;\n        cumulativeLength[0]=0f;\n        for(int i=1;i<POINTS;i++){float dx=path[i][0]-path[i-1][0],dy=path[i][1]-path[i-1][1],dz=path[i][2]-path[i-1][2];cumulativeLength[i]=cumulativeLength[i-1]+(float)Math.sqrt(dx*dx+dy*dy+dz*dz);}\n        trackLength=Math.max(1f,cumulativeLength[POINTS-1]);\n    }''')
R('''            float p=clamp(r.progress,0,.998f);float[] a=sample(p),b=sample(Math.min(.999f,p+.008f));\n            float dx=b[0]-a[0],dy=b[1]-a[1],dz=b[2]-a[2];float horiz=(float)Math.sqrt(dx*dx+dz*dz)+.001f;\n            float slope=clamp(-dy/horiz,-.35f,2.5f);float curvature=trackCurvature(p);\n            float accel=.0011f+.0048f*Math.max(0,slope);float rolling=.032f+.065f*Math.min(1f,curvature*.85f);\n            if(curvature>.85f&&slope>.12f)accel+=.0015f*Math.min(1.8f,curvature);\n            r.velocity+=accel*dt;r.velocity*=Math.max(.90f,1f-rolling*dt);\n            r.laneVelocity*=Math.max(.72f,1f-1.35f*dt);r.lane+=r.laneVelocity*dt;\n\n            applyCourseFeature(r,i,dt,p);\n            r.progress+=r.velocity*dt;\n            r.spin+=r.velocity*dt*760f;\n            if(r.air>0||r.airVelocity!=0){r.airVelocity-=9.81f*dt;r.air+=r.airVelocity*dt;if(r.air<0){r.air=0;r.airVelocity=0;r.velocity*=.985f;}}''','''            float p=clamp(r.progress,0,.998f);float[] a=sample(Math.max(.001f,p-.003f)),b=sample(Math.min(.999f,p+.003f));\n            float dx=b[0]-a[0],dy=b[1]-a[1],dz=b[2]-a[2];float ds=(float)Math.sqrt(dx*dx+dy*dy+dz*dz)+.001f;\n            float sinTheta=clamp(-dy/ds,-1f,1f);float curvature=trackCurvature(p);\n            float gravityAccel=(5f/7f)*9.81f*sinTheta;\n            float rollingResistance=.055f*9.81f*(float)Math.sqrt(Math.max(0f,1f-sinTheta*sinTheta));\n            float aeroDrag=.0065f*r.velocity*r.velocity;\n            float accel=gravityAccel-(r.velocity>0?rollingResistance:0f)-aeroDrag;\n            accel-=Math.min(1.4f,curvature*.42f)*r.velocity*.10f;\n            r.velocity=Math.max(.35f,r.velocity+accel*dt);\n            r.laneVelocity*=Math.max(.70f,1f-1.55f*dt);r.lane+=r.laneVelocity*dt;\n\n            applyCourseFeature(r,i,dt,p);\n            r.progress+=worldDistanceToProgress(r.velocity*dt,p);\n            r.spin+=(r.velocity/.68f)*dt*57.2958f;\n            if(r.air>0||r.airVelocity!=0){r.airVelocity-=9.81f*dt;r.air+=r.airVelocity*dt;if(r.air<0){r.air=0;r.airVelocity=0;r.velocity*=.965f;}}''')
a=s.index('    private void applyCourseFeature('); b=s.index('    private float trackCurvature',a)
s=s[:a]+'''    private void applyCourseFeature(Racer r,int i,float dt,float p){\n        if(in(p,.20f,.285f)){int row=Math.max(0,Math.min(11,(int)((p-.20f)/.085f*12f)));float stagger=((row&1)==0?0f:.43f);float nearest=Math.round((r.lane-stagger)/.86f)*.86f+stagger;float delta=r.lane-nearest;if(Math.abs(delta)<.34f){float dir=delta>=0?1f:-1f;r.laneVelocity+=dir*(1.7f+Math.min(2.2f,r.velocity*.08f))*dt*7f;r.velocity*=Math.max(.965f,1f-.030f*dt*8f);}r.laneVelocity+=(float)Math.sin(row*1.91f+i*.77f)*.20f*dt;}\n        if(in(p,.315f,.34f)){float desired=(float)Math.sin(p*92f+i*.8f)*2.0f;r.laneVelocity+=(desired-r.lane)*1.35f*dt;}\n        if(in(p,.455f,.475f))r.velocity+=5.0f*dt;\n        if(p>.492f&&p<.501f&&r.air==0&&r.airVelocity==0){r.airVelocity=5.6f+(i%3)*.18f;r.velocity+=1.2f;}\n        if(in(p,.57f,.645f)){float q=(p-.57f)/.075f;float radius=2.9f*(1f-q)+.35f;float omega=Math.max(1.4f,r.velocity/Math.max(.55f,radius));r.funnelAngle+=dt*omega;r.lane=(float)Math.sin(r.funnelAngle)*radius;r.velocity*=Math.max(.985f,1f-.018f*dt);}\n        if(p>.645f&&p<.655f)r.velocity+=1.8f*dt;\n        if(in(p,.70f,.755f)){float blocker=(float)Math.sin(totalTime*2.3f+p*24f)*2.5f;if(Math.abs(r.lane-blocker)<.60f){r.velocity*=Math.max(.90f,1f-1.30f*dt);r.laneVelocity+=(r.lane>=blocker?1:-1)*1.6f*dt;}}\n        if(in(p,.805f,.825f)&&Math.abs(r.lane)<1.15f)r.velocity+=5.8f*dt;\n        if(in(p,.87f,.925f)&&rng.nextFloat()<dt*1.4f){r.laneVelocity+=(rng.nextFloat()-.5f)*1.25f;r.velocity*=.994f;}\n        if(mapIndex%4==1&&in(p,.12f,.15f))r.velocity*=Math.max(.97f,1f-.055f*dt);\n        if(mapIndex%4==2&&in(p,.52f,.55f))r.laneVelocity+=(float)Math.sin(totalTime*4+i)*.40f*dt;\n        if(mapIndex%4==3&&in(p,.66f,.69f))r.velocity+=2.0f*dt;\n        r.velocity=clamp(r.velocity,.35f,34f);\n    }\n    private float worldDistanceToProgress(float distance,float p){float idx=clamp(p,0,1)*(POINTS-1);int i=Math.min(POINTS-2,Math.max(0,(int)idx));float target=cumulativeLength[i]+Math.max(0,distance);if(target>=trackLength)return 1f-p;int lo=i,hi=POINTS-1;while(lo+1<hi){int m=(lo+hi)>>>1;if(cumulativeLength[m]<target)lo=m;else hi=m;}float seg=Math.max(.001f,cumulativeLength[hi]-cumulativeLength[lo]);float q=(target-cumulativeLength[lo])/seg;float newP=(lo+q)/(POINTS-1f);return Math.max(0,newP-p);}\n\n'''+s[b:]
R('''                float sep=(1.0f-dl)*.5f+.05f;float dir=(a.lane<=b.lane?-1f:1f);a.laneVelocity+=dir*sep;b.laneVelocity-=dir*sep;\n                float av=(a.velocity+b.velocity)*.5f;a.velocity=av*.992f+(rng.nextFloat()-.5f)*.00012f;b.velocity=av*.992f+(rng.nextFloat()-.5f)*.00012f;''','''                float sep=(1.0f-dl)*.48f+.04f;float dir=(a.lane<=b.lane?-1f:1f);a.laneVelocity+=dir*sep;b.laneVelocity-=dir*sep;\n                float restitution=.72f;float va=a.velocity,vb=b.velocity;a.velocity=Math.max(.35f,(va+vb-restitution*(va-vb))*.5f);b.velocity=Math.max(.35f,(va+vb+restitution*(va-vb))*.5f);''')
R('float k=state==RUNNING?.115f:.18f;','float k=state==RUNNING?.075f:.16f;')
R('''        // main gravity track\n        for(int i=0;i<POINTS-1;i+=2){float[] a=path[i],b=path[Math.min(POINTS-1,i+2)];drawBeam(a,b,3.6f,.32f,new float[]{.20f,.22f,.28f},.42f,.20f,.05f,.72f);drawRail(a,b,theme,1);drawRail(a,b,theme,-1);}\n        for(int i=0;i<POINTS;i+=11){float[] p=path[i];drawBox(p[0],p[1]-5.2f,p[2],.75f,9.6f,.75f,new float[]{.055f,.06f,.075f},0,.9f,.35f,0,1);}''','''        // Solid colored 3D track: mostly opaque deck, translucent safety walls, bright theme stripe.\n        float[] deck={.10f+.28f*theme[0],.11f+.22f*theme[1],.14f+.18f*theme[2]};\n        float[] deckHi={.18f+.42f*theme[0],.18f+.34f*theme[1],.20f+.26f*theme[2]};\n        for(int i=0;i<POINTS-1;i+=2){float[] a=path[i],b=path[Math.min(POINTS-1,i+2)];drawBeam(a,b,3.7f,.40f,deck,.58f,.28f,.03f,.94f);drawBeam(new float[]{a[0],a[1]+.43f,a[2]},new float[]{b[0],b[1]+.43f,b[2]},.78f,.045f,deckHi,.42f,.18f,.32f,.96f);drawRail(a,b,theme,1);drawRail(a,b,theme,-1);drawWall(a,b,theme,1);drawWall(a,b,theme,-1);}\n        for(int i=0;i<POINTS;i+=11){float[] p=path[i];drawBox(p[0],p[1]-5.2f,p[2],.78f,9.6f,.78f,new float[]{.075f+.12f*theme[0],.07f+.08f*theme[1],.085f+.06f*theme[2]},0,.82f,.34f,0,1);}''')
R('new float[]{.22f,.25f,.31f},0,.18f,.22f,.08f,.34f)','new float[]{.16f+.20f*color[0],.17f+.16f*color[1],.20f+.12f*color[2]},0,.30f,.26f,.06f,.82f)')
R('draw(cube,color,.38f,.17f,.10f,.58f);','draw(cube,color,.44f,.20f,.10f,.84f);')
R('drawSphereMaterial(c[0]+(float)Math.cos(rad)*radius,c[1]+.9f-(j/15f)*1.1f,c[2]+(float)Math.sin(rad)*radius,.20f,color,.30f,.18f,.16f,.62f,0);','drawSphereMaterial(c[0]+(float)Math.cos(rad)*radius,c[1]+.9f-(j/15f)*1.1f,c[2]+(float)Math.sin(rad)*radius,.23f,color,.38f,.21f,.12f,.88f,0);')
R('    private void drawRail(float[] a,float[] b,float[] color,int side){','    private void drawWall(float[] a,float[] b,float[] color,int side){float dx=b[0]-a[0],dz=b[2]-a[2],l=(float)Math.sqrt(dx*dx+dz*dz)+.001f;float ox=-dz/l*3.58f*side,oz=dx/l*3.58f*side;float[] aa={a[0]+ox,a[1]+1.15f,a[2]+oz},bb={b[0]+ox,b[1]+1.15f,b[2]+oz};float[] glass={.18f+.40f*color[0],.20f+.28f*color[1],.23f+.22f*color[2]};drawBeam(aa,bb,.10f,1.05f,glass,.22f,.18f,.08f,.58f);}\n    private void drawRail(float[] a,float[] b,float[] color,int side){')
old='private static final String FS="#version 300 es\\nprecision mediump float;in vec3 vN;in vec3 vP;uniform vec3 uColor;uniform vec3 uLight;uniform vec3 uCamera;uniform float uMetallic;uniform float uRoughness;uniform float uAlpha;uniform float uEmissive;out vec4 frag;void main(){vec3 n=normalize(vN);vec3 l=normalize(uLight);vec3 v=normalize(uCamera-vP);vec3 h=normalize(l+v);float ndl=max(dot(n,l),0.0);float ndh=max(dot(n,h),0.0);float fres=pow(1.0-max(dot(n,v),0.0),5.0);float shin=mix(18.0,210.0,1.0-clamp(uRoughness,0.0,1.0));float spec=pow(ndh,shin);vec3 f0=mix(vec3(0.04),uColor,clamp(uMetallic,0.0,1.0));vec3 diffuse=uColor*(0.08+0.92*ndl)*(1.0-uMetallic*.72);vec3 reflection=f0*(spec*(1.18-uRoughness*.55)+fres*(0.46+0.62*uMetallic));vec3 sky=mix(vec3(0.03,0.04,0.07),vec3(0.40,0.49,0.67),clamp(n.y*.5+.5,0.0,1.0))*fres*.38;vec3 c=diffuse+reflection+sky+uColor*uEmissive;frag=vec4(c,uAlpha);}";'
new='private static final String FS="#version 300 es\\nprecision highp float;in vec3 vN;in vec3 vP;uniform vec3 uColor;uniform vec3 uLight;uniform vec3 uCamera;uniform float uMetallic;uniform float uRoughness;uniform float uAlpha;uniform float uEmissive;out vec4 frag;void main(){vec3 n=normalize(vN);vec3 v=normalize(uCamera-vP);vec3 l1=normalize(vec3(-.35,.92,.28));vec3 l2=normalize(vec3(.65,.35,-.58));float d1=max(dot(n,l1),0.0);float d2=max(dot(n,l2),0.0);vec3 h=normalize(l1+v);float ndh=max(dot(n,h),0.0);float rough=clamp(uRoughness,.04,1.0);float shin=mix(22.0,260.0,1.0-rough);float spec=pow(ndh,shin);float fres=pow(1.0-max(dot(n,v),0.0),5.0);float rim=pow(1.0-max(dot(n,v),0.0),2.4);vec3 f0=mix(vec3(.045),uColor,clamp(uMetallic,0.0,1.0));vec3 ambient=uColor*vec3(.095,.105,.135);vec3 diffuse=uColor*(.86*d1+.24*d2)*(1.0-uMetallic*.62);vec3 reflection=f0*(spec*(1.45-rough*.55)+fres*.72);vec3 sky=mix(vec3(.025,.03,.055),vec3(.38,.48,.68),clamp(n.y*.5+.5,0.0,1.0))*(.11+.32*fres);vec3 c=ambient+diffuse+reflection+sky+uColor*uEmissive+uColor*rim*.08;c=c/(c+vec3(.72));c=pow(c,vec3(.78));frag=vec4(c,uAlpha);}";'
R(old,new)
p.write_text(s)
b=Path('mm060/app/build.gradle');t=b.read_text();t=re.sub(r'versionCode\s+\d+','versionCode 6',t);t=re.sub(r"versionName\s+'[^']+'","versionName '0.6.0'",t);b.write_text(t)
