from pathlib import Path
p=Path('app/src/main/assets/www/game.js')
s=p.read_text()

# Replace generic/incorrect active-skill upgrade wording with descriptions that belong to each skill.
old="function choice(){if(run.choosing)return;run.choosing=true;let pool=[...SKILLS].filter(k=>!ACTIVE.includes(k)||activeEnabled(k)).sort(()=>Math.random()-.5).slice(0,3),el=$('#choiceList');el.innerHTML='';pool.forEach(k=>{let b=document.createElement('button');b.className='choice';let note=ACTIVE.includes(k)?'Rank 10 transforms permanently; Rank 20 retrains a lost skill; Rank 30 restores another slot.':'Permanent skill improvement';b.innerHTML=`<b>${k.toUpperCase()} • Rank ${rank(k)+1}</b><span>${note}</span>`;b.onclick=()=>{save.character.skills[k]=(save.character.skills[k]||0)+1;if(save.mastery.halfDamage[k]?.active&&rank(k)>10)delete save.mastery.halfDamage[k];if(k==='heal')run.p.hp=Math.min(run.p.maxHp,run.p.hp+run.p.maxHp*.35);persist();Object.assign(run.p,stats());run.choosing=false;$('#choiceOverlay').classList.add('hidden');checkMastery(k);syncSkills()};el.appendChild(b)});$('#choiceOverlay').classList.remove('hidden')}"
new="""const SKILL_DESCRIPTIONS={fire:'FIRE • Increases burning damage, burn duration and fiery projectiles. Higher ranks evolve into fire novas, infernos and devastating battlefield burns.',frost:'FROST • Increases frost damage, chill and freeze control. Higher ranks evolve into frost novas, ice barrages and stronger battlefield freezes.',poison:'POISON • Increases poison damage, toxic duration and poison area. Higher ranks evolve into toxic volleys, larger poison pools and stronger damage-over-time.',blades:'BLADES • Increases spinning and thrown blade damage. Higher ranks add permanent blade rings, extra outer blades and increasingly powerful blade storms.',rate:'ATTACK SPEED • Permanently increases the speed of your normal attacks.',power:'POWER • Permanently increases your base attack damage.',double:'DOUBLE ATTACK • Increases the chance for normal attacks to fire an additional shot.',crit:'CRITICAL • Increases critical-hit chance.',speed:'MOVE SPEED • Permanently increases movement speed.',heal:'HEAL • Immediately restores health and improves this permanent skill rank.',recovery:'RECOVERY • Increases passive life recovery.',pierce:'PIERCE • Allows normal projectiles to pass through additional enemies.',multi:'MULTI SHOT • Adds additional projectiles to normal attacks.',lifesteal:'LIFE STEAL • Returns a portion of damage dealt as health.'};\nfunction choice(){if(run.choosing)return;run.choosing=true;let pool=[...SKILLS].filter(k=>!ACTIVE.includes(k)||activeEnabled(k)).sort(()=>Math.random()-.5).slice(0,3),el=$('#choiceList');el.innerHTML='';pool.forEach(k=>{let b=document.createElement('button');b.className='choice';let note=SKILL_DESCRIPTIONS[k]||'Permanent skill improvement';if(ACTIVE.includes(k))note+=` Rank ${rank(k)+1}. Rank 10 mastery makes this skill permanent; Rank 20/30 unlock mastery recovery choices.`;b.innerHTML=`<b>${k.toUpperCase()} • Rank ${rank(k)+1}</b><span>${note}</span>`;b.onclick=()=>{save.character.skills[k]=(save.character.skills[k]||0)+1;if(save.mastery.halfDamage[k]?.active&&rank(k)>10)delete save.mastery.halfDamage[k];if(k==='heal')run.p.hp=Math.min(run.p.maxHp,run.p.hp+run.p.maxHp*.35);persist();Object.assign(run.p,stats());run.choosing=false;$('#choiceOverlay').classList.add('hidden');checkMastery(k);syncSkills()};el.appendChild(b)});$('#choiceOverlay').classList.remove('hidden')}"""
if old not in s: raise SystemExit('missing choice renderer')
s=s.replace(old,new,1)

# Add visible world-space Mythic FX. v1.1.0 already applies the mechanical damage/status effects;
# this layer makes those powers visibly happen in combat and adds persistent damaging Flamewake ground fire.
append=r'''

const evolveSkillsV111=evolveSkills;
evolveSkills=function(dt){evolveSkillsV111(dt);mythicVisualTick(dt)};
function addMythicFx(type,x,y,r,life=1){run.mythicFx=run.mythicFx||[];run.mythicFx.push({type,x,y,r,life,max:life,seed:Math.random()*6.28})}
function mythicVisualTick(dt){if(!run||!run.p)return;let lv=equippedMythicLevels();run.mythicFx=run.mythicFx||[];run.mythicFxClock=(run.mythicFxClock||0)-dt;run.flamewakeClock=(run.flamewakeClock||0)-dt;
 if(lv[3]&&rank('fire')>0&&activeEnabled('fire')&&run.flamewakeClock<=0){let L=lv[3];run.mythicFx.push({type:'flamewake',x:run.p.x,y:run.p.y,r:52+L*7,life:2.8+L*.35,max:2.8+L*.35,dps:mythicDamage(.32+.08*L)});run.flamewakeClock=Math.max(.16,.34-.035*L)}
 for(const f of run.mythicFx){f.life-=dt;if(f.type==='flamewake'){for(const e of run.enemies)if(e.area===run.area&&Math.hypot(e.x-f.x,e.y-f.y)<f.r+e.r){e.hp-=f.dps*dt;e.burn=Math.max(e.burn,.6);e.burnDps=Math.max(e.burnDps,run.p.burnDps*(.65+.12*(lv[3]||1)))}}}
 run.mythicFx=run.mythicFx.filter(f=>f.life>0);
 if(run.mythicFxClock<=0){run.mythicFxClock=.42;for(const id in lv){let L=lv[id],rad=90+L*14;if(id==0||id==1||id==2||id==4)addMythicFx('fire',run.p.x,run.p.y,rad,.55);else if(id>=5&&id<=9)addMythicFx('frost',run.p.x,run.p.y,rad,.65);else if(id>=10&&id<=14)addMythicFx('poison',run.p.x,run.p.y,rad,.7);else if(id>=15&&id<=22)addMythicFx(id==15?'fireblade':id==16?'frostblade':id==17?'poisonblade':'blade',run.p.x,run.p.y,rad,.5);else if(id==27)addMythicFx('time',run.p.x,run.p.y,170+L*18,.75);else if(id==29)addMythicFx('cataclysm',run.p.x,run.p.y,220+L*25,.8)}}}
}
function drawMythicFx(){if(!run||!run.mythicFx)return;for(const f of run.mythicFx){let x=sx(f.x),y=sy(f.y),a=Math.max(0,f.life/f.max),pulse=1+(1-a)*.22;ctx.save();ctx.translate(x,y);ctx.globalAlpha=Math.min(.82,.18+a*.58);if(f.type==='fire'||f.type==='flamewake'||f.type==='fireblade'){let g=ctx.createRadialGradient(0,0,4,0,0,f.r*pulse);g.addColorStop(0,'#fff1a8');g.addColorStop(.28,'#ff9a2e');g.addColorStop(.72,'#e83e18aa');g.addColorStop(1,'#5b130000');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,f.r*pulse,0,7);ctx.fill();for(let i=0;i<7;i++){let q=f.seed+i*.9+run.time*2.5,rr=f.r*(.25+.55*((i%3)/3));ctx.fillStyle=i%2?'#ffd05a':'#ff5b24';ctx.beginPath();ctx.arc(Math.cos(q)*rr,Math.sin(q)*rr,3+4*a,0,7);ctx.fill()}}else if(f.type==='frost'||f.type==='frostblade'){ctx.strokeStyle='#c9f5ff';ctx.lineWidth=3+3*a;for(let i=0;i<8;i++){let q=i*.785+f.seed;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(Math.cos(q)*f.r*pulse,Math.sin(q)*f.r*pulse);ctx.stroke()}ctx.strokeStyle='#76cfff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,f.r*pulse,0,7);ctx.stroke()}else if(f.type==='poison'||f.type==='poisonblade'){ctx.fillStyle='#55d23c55';ctx.beginPath();ctx.arc(0,0,f.r*pulse,0,7);ctx.fill();ctx.strokeStyle='#9aff69';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,f.r*pulse,0,7);ctx.stroke();for(let i=0;i<9;i++){let q=f.seed+i*.7,rr=f.r*(.2+.65*((i%4)/4));ctx.fillStyle='#8cf35c';ctx.beginPath();ctx.arc(Math.cos(q)*rr,Math.sin(q)*rr,3+2*a,0,7);ctx.fill()}}else if(f.type==='blade'){ctx.strokeStyle='#f2f2ff';ctx.lineWidth=3;for(let i=0;i<10;i++){let q=f.seed+i*.628+run.time*5;ctx.beginPath();ctx.moveTo(Math.cos(q)*f.r*.55,Math.sin(q)*f.r*.55);ctx.lineTo(Math.cos(q)*f.r,Math.sin(q)*f.r);ctx.stroke()}}else if(f.type==='time'){ctx.strokeStyle='#c884ff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,f.r*pulse,0,7);ctx.stroke();ctx.strokeStyle='#8d63ff88';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,f.r*.7*pulse,0,7);ctx.stroke()}else if(f.type==='cataclysm'){ctx.strokeStyle='#fff0a8';ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,0,f.r*pulse,0,7);ctx.stroke();ctx.strokeStyle='#ff6a2a';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,f.r*.7*pulse,0,7);ctx.stroke()}ctx.restore()}}
const drawV111=draw;
draw=function(){drawV111();drawMythicFx()};
'''
s += append
p.write_text(s)
