from pathlib import Path
p=Path('app/src/main/assets/www/game.js')
s=p.read_text();end='})();'
if end not in s: raise SystemExit('missing game closure')
block=r'''
const SKILL_DESCRIPTIONS_V111={fire:'FIRE • More burn damage, burn duration and fiery projectiles. Evolves into fire novas, infernos and battlefield burns.',frost:'FROST • More frost damage, chill and freeze control. Evolves into frost novas, ice barrages and stronger freezes.',poison:'POISON • More poison damage, toxic duration and poison area. Evolves into toxic volleys, larger poison pools and stronger damage-over-time.',blades:'BLADES • More spinning and thrown blade damage. Evolves into permanent blade rings, outer blades and blade storms.',rate:'ATTACK SPEED • Permanently increases normal attack speed.',power:'POWER • Permanently increases base attack damage.',double:'DOUBLE ATTACK • Increases the chance to fire an additional normal shot.',crit:'CRITICAL • Increases critical-hit chance.',speed:'MOVE SPEED • Permanently increases movement speed.',heal:'HEAL • Immediately restores health and improves this skill rank.',recovery:'RECOVERY • Increases passive life recovery.',pierce:'PIERCE • Normal projectiles pass through additional enemies.',multi:'MULTI SHOT • Adds projectiles to normal attacks.',lifesteal:'LIFE STEAL • Returns a portion of damage dealt as health.'};
choice=function(){if(run.choosing)return;run.choosing=true;let pool=[...SKILLS].filter(k=>(!ACTIVE.includes(k)||activeEnabled(k))&&(ACTIVE.includes(k)?rank(k)<50:rank(k)<30)).sort(()=>Math.random()-.5).slice(0,3),el=$('#choiceList');el.innerHTML='';pool.forEach(k=>{let b=document.createElement('button');b.className='choice';let note=SKILL_DESCRIPTIONS_V111[k]||'Permanent skill improvement';if(ACTIVE.includes(k))note+=` Rank ${rank(k)+1}. Rank 10 mastery makes this skill permanent; Rank 20/30 unlock mastery recovery choices.`;b.innerHTML=`<b>${k.toUpperCase()} • Rank ${rank(k)+1}</b><span>${note}</span>`;b.onclick=()=>{save.character.skills[k]=(save.character.skills[k]||0)+1;if(save.mastery.halfDamage[k]?.active&&rank(k)>10)delete save.mastery.halfDamage[k];if(k==='heal')run.p.hp=Math.min(run.p.maxHp,run.p.hp+run.p.maxHp*.35);persist();Object.assign(run.p,stats());run.choosing=false;$('#choiceOverlay').classList.add('hidden');checkMastery(k);syncSkills()};el.appendChild(b)});$('#choiceOverlay').classList.remove('hidden')};
const evolveSkillsV111=evolveSkills;evolveSkills=function(dt){evolveSkillsV111(dt);mythicVisualTick(dt)};
function addMythicFx(type,x,y,r,life=1){run.mythicFx=run.mythicFx||[];run.mythicFx.push({type,x,y,r,life,max:life,seed:Math.random()*6.28})}
function mythicVisualTick(dt){if(!run||!run.p)return;let lv=equippedMythicLevels();run.mythicFx=run.mythicFx||[];run.mythicFxClock=(run.mythicFxClock||0)-dt;run.flamewakeClock=(run.flamewakeClock||0)-dt;if(lv[3]&&rank('fire')>0&&activeEnabled('fire')&&run.flamewakeClock<=0){let L=lv[3];run.mythicFx.push({type:'flamewake',x:run.p.x,y:run.p.y,r:52+L*7,life:2.8+L*.35,max:2.8+L*.35,dps:mythicDamage(.32+.08*L),seed:Math.random()*6.28});run.flamewakeClock=Math.max(.16,.34-.035*L)}for(const f of run.mythicFx){f.life-=dt;if(f.type==='flamewake')for(const e of run.enemies)if(e.area===run.area&&Math.hypot(e.x-f.x,e.y-f.y)<f.r+e.r){e.hp-=f.dps*dt;e.burn=Math.max(e.burn,.6);e.burnDps=Math.max(e.burnDps,run.p.burnDps*(.65+.12*(lv[3]||1)))}}run.mythicFx=run.mythicFx.filter(f=>f.life>0);if(run.mythicFxClock<=0){run.mythicFxClock=.42;for(const id in lv){let L=lv[id],rad=90+L*14;if(id==0||id==1||id==2||id==4)addMythicFx('fire',run.p.x,run.p.y,rad,.55);else if(id>=5&&id<=9)addMythicFx('frost',run.p.x,run.p.y,rad,.65);else if(id>=10&&id<=14)addMythicFx('poison',run.p.x,run.p.y,rad,.7);else if(id>=15&&id<=22)addMythicFx(id==15?'fireblade':id==16?'frostblade':id==17?'poisonblade':'blade',run.p.x,run.p.y,rad,.5);else if(id==27)addMythicFx('time',run.p.x,run.p.y,170+L*18,.75);else if(id==29)addMythicFx('cataclysm',run.p.x,run.p.y,220+L*25,.8)}}}
function drawMythicFx(){if(!run||!run.mythicFx)return;for(const f of run.mythicFx){let x=sx(f.x),y=sy(f.y),a=Math.max(0,f.life/f.max),pulse=1+(1-a)*.22;ctx.save();ctx.translate(x,y);ctx.globalAlpha=Math.min(.82,.18+a*.58);if(f.type==='fire'||f.type==='flamewake'||f.type==='fireblade'){let g=ctx.createRadialGradient(0,0,4,0,0,f.r*pulse);g.addColorStop(0,'#fff1a8');g.addColorStop(.28,'#ff9a2e');g.addColorStop(.72,'#e83e18aa');g.addColorStop(1,'#5b130000');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,f.r*pulse,0,7);ctx.fill();for(let i=0;i<7;i++){let q=f.seed+i*.9+run.time*2.5,rr=f.r*(.25+.55*((i%3)/3));ctx.fillStyle=i%2?'#ffd05a':'#ff5b24';ctx.beginPath();ctx.arc(Math.cos(q)*rr,Math.sin(q)*rr,3+4*a,0,7);ctx.fill()}}else if(f.type==='frost'||f.type==='frostblade'){ctx.strokeStyle='#c9f5ff';ctx.lineWidth=3+3*a;for(let i=0;i<8;i++){let q=i*.785+f.seed;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(Math.cos(q)*f.r*pulse,Math.sin(q)*f.r*pulse);ctx.stroke()}ctx.strokeStyle='#76cfff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,f.r*pulse,0,7);ctx.stroke()}else if(f.type==='poison'||f.type==='poisonblade'){ctx.fillStyle='#55d23c55';ctx.beginPath();ctx.arc(0,0,f.r*pulse,0,7);ctx.fill();ctx.strokeStyle='#9aff69';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,f.r*pulse,0,7);ctx.stroke()}else if(f.type==='blade'){ctx.strokeStyle='#f2f2ff';ctx.lineWidth=3;for(let i=0;i<10;i++){let q=f.seed+i*.628+run.time*5;ctx.beginPath();ctx.moveTo(Math.cos(q)*f.r*.55,Math.sin(q)*f.r*.55);ctx.lineTo(Math.cos(q)*f.r,Math.sin(q)*f.r);ctx.stroke()}}else if(f.type==='time'){ctx.strokeStyle='#c884ff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,f.r*pulse,0,7);ctx.stroke()}else if(f.type==='cataclysm'){ctx.strokeStyle='#fff0a8';ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,0,f.r*pulse,0,7);ctx.stroke()}ctx.restore()}}
const drawV111=draw;draw=function(){drawV111();drawMythicFx()};
'''
head,tail=s.rsplit(end,1);s=head+'\n'+block+'\n'+end+tail;p.write_text(s)
