package com.brokengeargaming.torquematch;

import android.animation.*;import android.content.*;import android.graphics.*;import android.media.*;import android.os.*;import android.view.*;import android.view.animation.DecelerateInterpolator;import java.util.*;

public class TorqueMatchView extends View{
 static final int R=8,C=8; static final long SW=330,CL=300,FA=440,PA=240; Paint p=new Paint(1),tx=new Paint(1); Random rnd=new Random(); SharedPreferences pref; Handler h=new Handler(Looper.getMainLooper()); Tile[][] b=new Tile[R][C]; RectF start=new RectF(),next=new RectF(); State state=State.MENU; int level,score,moves,target,startMoves,stars,reward,totalCredits; float left,top,cell,w,hh,downX,downY; int dr=-1,dc=-1; boolean used,locked,swapAnim; int r1,c1,r2,c2; float sp,cp,fp=1; Set<Integer> clearing=new HashSet<>(); Map<Long,Float> fall=new HashMap<>(); int chain; String banner=""; long bannerUntil,celebrateAt; static long nid=1; SoundPool sounds; int sndSwap,sndMatch,sndCombo,sndWin,sndReward;
 enum State{MENU,PLAYING,COMPLETE_ANIM,COMPLETE,FAILED} enum Kind{WHEEL,ROTOR,TURBO,SPARK,GEAR,PISTON} enum Special{NONE,ROW,COL,HYPER}
 static class Tile{final long id=nid++;Kind k;Special s=Special.NONE;Tile(Kind x){k=x;}}
 static class MI{Set<Integer> cells=new HashSet<>();List<Integer> lens=new ArrayList<>();int runs;}
 public TorqueMatchView(Context x){super(x);setLayerType(1,null);pref=x.getSharedPreferences("torque_match",0);level=Math.max(1,pref.getInt("level",1));totalCredits=pref.getInt("credits",0);tx.setTypeface(Typeface.create("sans",1));initSound();}
 void initSound(){sounds=new SoundPool.Builder().setMaxStreams(6).setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_GAME).setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION).build()).build();sndSwap=loadTone(260,95,.20);sndMatch=loadTone(430,150,.32);sndCombo=loadTone(650,220,.38);sndWin=loadTone(820,520,.42);sndReward=loadTone(1040,240,.32);}
 int loadTone(double hz,int ms,double vol){int sr=22050,n=sr*ms/1000;byte[] pcm=new byte[n*2];for(int i=0;i<n;i++){double env=Math.sin(Math.PI*i/n);double wave=Math.sin(2*Math.PI*hz*i/sr)+.35*Math.sin(2*Math.PI*hz*1.5*i/sr);short v=(short)(wave*env*vol*32767/1.35);pcm[i*2]=(byte)v;pcm[i*2+1]=(byte)(v>>8);} try{java.io.File f=java.io.File.createTempFile("tm",".wav",getContext().getCacheDir());java.io.FileOutputStream o=new java.io.FileOutputStream(f);writeWav(o,pcm,sr);o.close();return sounds.load(f.getAbsolutePath(),1);}catch(Exception e){return 0;}}
 void writeWav(java.io.OutputStream o,byte[] d,int sr)throws Exception{int len=d.length;java.nio.ByteBuffer q=java.nio.ByteBuffer.allocate(44).order(java.nio.ByteOrder.LITTLE_ENDIAN);q.put("RIFF".getBytes());q.putInt(36+len);q.put("WAVEfmt ".getBytes());q.putInt(16);q.putShort((short)1);q.putShort((short)1);q.putInt(sr);q.putInt(sr*2);q.putShort((short)2);q.putShort((short)16);q.put("data".getBytes());q.putInt(len);o.write(q.array());o.write(d);}
 void play(int id,float rate){if(id!=0)sounds.play(id,.7f,.7f,1,0,rate);}
 protected void onSizeChanged(int a,int z,int x,int y){w=a;hh=z;cell=Math.min((a-32f)/C,(z*.62f)/R);left=(a-cell*C)/2;top=z*.24f;}
 protected void onDraw(Canvas c){c.drawColor(Color.rgb(11,11,13));p.setColor(Color.rgb(31,31,36));for(int y=0;y<hh;y+=56)c.drawRect(0,y,w,y+2,p);if(state==State.MENU)menu(c);else game(c);if(state==State.COMPLETE_ANIM){celebrate(c);postInvalidateOnAnimation();}}
 void menu(Canvas c){center(c,"TORQUE MATCH",hh*.18f,w*.09f,Color.WHITE);center(c,"GARAGE MATCH-3",hh*.235f,w*.043f,0xffff7316);wheel(c,w/2,hh*.38f,Math.min(w,hh)*.15f);center(c,"Swipe parts. Build combos. Earn garage credits.",hh*.57f,w*.034f,Color.LTGRAY);float bw=w*.7f,bh=hh*.085f;start.set((w-bw)/2,hh*.67f,(w+bw)/2,hh*.67f+bh);button(c,start,"PLAY LEVEL "+level);center(c,"GARAGE CREDITS  "+totalCredits,hh*.80f,w*.038f,0xffffcc15);}
 void game(Canvas c){center(c,"LEVEL "+level,hh*.055f,w*.048f,Color.WHITE);center(c,"SCORE "+score+" / "+target,hh*.102f,w*.041f,0xffff7316);center(c,"MOVES  "+moves,hh*.145f,w*.042f,moves<=5?0xffef4444:Color.LTGRAY);if(!banner.isEmpty()&&System.currentTimeMillis()<bannerUntil){center(c,banner,hh*.195f,w*.04f,0xffffcc15);postInvalidateOnAnimation();}RectF tray=new RectF(left-8,top-8,left+cell*C+8,top+cell*R+8);p.setColor(0xff16161a);c.drawRoundRect(tray,22,22,p);for(int r=0;r<R;r++)for(int col=0;col<C;col++){Tile t=b[r][col];if(t==null)continue;float rr=r,cc=col;if(swapAnim){if(r==r1&&col==c1){rr=lerp(r1,r2,sp);cc=lerp(c1,c2,sp);}else if(r==r2&&col==c2){rr=lerp(r2,r1,sp);cc=lerp(c2,c1,sp);}}else if(fp<1&&fall.containsKey(t.id))rr=lerp(fall.get(t.id),r,fp);tile(c,rr,cc,t,clearing.contains(r*C+col)?1-cp:1);}if(state==State.COMPLETE||state==State.FAILED)result(c);}
 void tile(Canvas c,float r,float col,Tile t,float a){float x=left+col*cell,y=top+r*cell;p.setAlpha((int)(255*a));p.setColor(0xff27272d);c.drawRoundRect(new RectF(x+3,y+3,x+cell-3,y+cell-3),cell*.2f,cell*.2f,p);float cx=x+cell/2,cy=y+cell/2,s=cell*.29f;switch(t.k){case WHEEL:wheel(c,cx,cy,s);break;case ROTOR:p.setColor(0xffcbd5e1);c.drawCircle(cx,cy,s,p);p.setColor(0xffef4444);c.drawArc(new RectF(cx-s*.9f,cy-s*.9f,cx+s*.9f,cy+s*.9f),-30,70,true,p);break;case TURBO:p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(s*.24f);p.setColor(0xff38bdf8);c.drawCircle(cx,cy,s*.72f,p);p.setStyle(Paint.Style.FILL);break;case SPARK:p.setColor(Color.WHITE);c.drawRoundRect(new RectF(cx-s*.23f,cy-s*.8f,cx+s*.23f,cy+s*.35f),8,8,p);p.setColor(0xffffbf24);c.drawRect(cx-s*.09f,cy+s*.3f,cx+s*.09f,cy+s*.85f,p);break;case GEAR:p.setColor(0xffff7316);c.drawCircle(cx,cy,s*.74f,p);p.setColor(0xff27272a);c.drawCircle(cx,cy,s*.28f,p);break;case PISTON:p.setColor(0xffa3e635);c.drawRoundRect(new RectF(cx-s*.55f,cy-s*.65f,cx+s*.55f,cy-s*.05f),8,8,p);p.setStrokeWidth(s*.18f);c.drawLine(cx,cy,cx,cy+s*.7f,p);}p.setAlpha(255);}
 void wheel(Canvas c,float x,float y,float s){p.setColor(0xff121214);c.drawCircle(x,y,s,p);p.setColor(0xffa1a1aa);c.drawCircle(x,y,s*.72f,p);p.setColor(0xff28282c);c.drawCircle(x,y,s*.25f,p);}
 void celebrate(Canvas c){float t=Math.min(1,(System.currentTimeMillis()-celebrateAt)/1400f);for(int i=0;i<30;i++){double a=i*Math.PI*2/30;float rad=w*(.1f+.55f*t);p.setColor(i%2==0?0xffff7316:0xffffcc15);c.drawCircle(w/2+(float)Math.cos(a)*rad,hh*.45f+(float)Math.sin(a)*rad*.7f,8,p);}center(c,"LEVEL COMPLETE!",hh*.45f,w*.065f,Color.WHITE);}
 void result(Canvas c){p.setColor(0xeb08080a);c.drawRoundRect(new RectF(w*.06f,hh*.25f,w*.94f,hh*.76f),28,28,p);boolean win=state==State.COMPLETE;center(c,win?"GARAGE CLEARED!":"OUT OF MOVES",hh*.35f,w*.057f,win?0xffa3e635:0xffef4444);center(c,"FINAL SCORE  "+score,hh*.42f,w*.044f,Color.WHITE);if(win){String st=stars==3?"★ ★ ★":stars==2?"★ ★ ☆":"★ ☆ ☆";center(c,st,hh*.49f,w*.057f,0xffffcc15);center(c,"Moves left: "+moves+" / "+startMoves,hh*.54f,w*.034f,Color.LTGRAY);center(c,"REWARD  +"+reward+" GARAGE CREDITS",hh*.59f,w*.037f,0xffffcc15);center(c,"TOTAL  "+totalCredits,hh*.635f,w*.032f,Color.LTGRAY);}float bw=w*.62f,bh=hh*.07f;next.set((w-bw)/2,hh*.66f,(w+bw)/2,hh*.66f+bh);button(c,next,win?"NEXT LEVEL":"TRY AGAIN");}
 int calcStars(){float remain=moves/(float)Math.max(1,startMoves);if(remain>=.50f)return 3;if(remain>=.25f)return 2;return 1;} int calcReward(){int base=100+level*15;return base+(stars-1)*75+moves*8;}
 void begin(){h.removeCallbacksAndMessages(null);state=State.PLAYING;score=0;moves=Math.max(16,24-(level-1)/3);startMoves=moves;target=2800+(level-1)*950;locked=false;clearing.clear();fall.clear();fp=1;banner="";fill();invalidate();}
 void fill(){for(int r=0;r<R;r++)for(int c=0;c<C;c++){Kind k;do{k=Kind.values()[rnd.nextInt(6)];}while((c>=2&&b[r][c-1].k==k&&b[r][c-2].k==k)||(r>=2&&b[r-1][c].k==k&&b[r-2][c].k==k));b[r][c]=new Tile(k);}}
 public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();if(state==State.MENU){if(e.getAction()==1&&start.contains(x,y))begin();return true;}if(state==State.COMPLETE||state==State.FAILED){if(e.getAction()==1&&next.contains(x,y)){if(state==State.COMPLETE){level++;pref.edit().putInt("level",level).apply();}begin();}return true;}if(state!=State.PLAYING||locked)return true;if(e.getAction()==0){downX=x;downY=y;used=false;dc=(int)((x-left)/cell);dr=(int)((y-top)/cell);if(dr<0||dr>=R||dc<0||dc>=C)dr=dc=-1;}else if(e.getAction()==2&&dr>=0&&!used){float dx=x-downX,dy=y-downY;if(Math.abs(dx)>cell*.24||Math.abs(dy)>cell*.24){int nr=dr,nc=dc;if(Math.abs(dx)>Math.abs(dy))nc+=dx>0?1:-1;else nr+=dy>0?1:-1;if(nr>=0&&nr<R&&nc>=0&&nc<C){used=true;doSwap(dr,dc,nr,nc);}}}else if(e.getAction()==1)dr=dc=-1;return true;}
 void doSwap(int a,int d,int z,int q){locked=true;swapAnim=true;r1=a;c1=d;r2=z;c2=q;play(sndSwap,1);anim(SW,v->{sp=v;invalidate();},()->{swapAnim=false;swap(a,d,z,q);MI m=find();if(m.cells.isEmpty()){swapAnim=true;r1=z;c1=q;r2=a;c2=d;anim(SW,v->{sp=v;invalidate();},()->{swapAnim=false;swap(a,d,z,q);locked=false;invalidate();});}else{moves--;chain=1;resolve(m);}});}
 void resolve(MI m){Set<Integer> ex=new HashSet<>(m.cells);int gain=points(m,chain);score+=gain;banner=(chain>1?"WAVE x"+chain+"  ":"")+"+"+gain;bannerUntil=System.currentTimeMillis()+900;play(chain>1?sndCombo:sndMatch,Math.min(1.5f,1f+(chain-1)*.08f));clearing.clear();clearing.addAll(ex);cp=0;anim(CL,v->{cp=v;invalidate();},()->{for(int pos:ex)b[pos/C][pos%C]=null;clearing.clear();gravity();anim(FA,v->{fp=v;invalidate();},()->{fp=1;fall.clear();h.postDelayed(()->{MI n=find();if(!n.cells.isEmpty()){chain++;resolve(n);}else finish();},PA);});});}
 int points(MI m,int ch){int base=0;for(int len:m.lens)base+=len==3?300:len==4?700:len==5?1300:1300+(len-5)*650;return Math.round(base*(1+Math.max(0,m.runs-1)*.4f)*(1+Math.max(0,ch-1)*.6f));}
 void finish(){locked=false;if(score>=target){stars=calcStars();reward=calcReward();totalCredits+=reward;pref.edit().putInt("credits",totalCredits).apply();play(sndWin,1);h.postDelayed(()->play(sndReward,1.08f),350);state=State.COMPLETE_ANIM;celebrateAt=System.currentTimeMillis();invalidate();h.postDelayed(()->{state=State.COMPLETE;invalidate();},1400);}else if(moves<=0){state=State.FAILED;invalidate();}}
 void gravity(){fall.clear();for(int c=0;c<C;c++){int wr=R-1;for(int r=R-1;r>=0;r--)if(b[r][c]!=null){Tile t=b[r][c];if(wr!=r){b[wr][c]=t;b[r][c]=null;fall.put(t.id,(float)r);}wr--;}int si=0;while(wr>=0){Tile t=new Tile(Kind.values()[rnd.nextInt(6)]);b[wr][c]=t;fall.put(t.id,-1f-si++);wr--;}}fp=0;}
 MI find(){MI m=new MI();for(int r=0;r<R;r++){int c=0;while(c<C){if(b[r][c]==null){c++;continue;}Kind k=b[r][c].k;int e=c+1;while(e<C&&b[r][e]!=null&&b[r][e].k==k)e++;int len=e-c;if(len>=3){m.runs++;m.lens.add(len);for(int x=c;x<e;x++)m.cells.add(r*C+x);}c=e;}}for(int c=0;c<C;c++){int r=0;while(r<R){if(b[r][c]==null){r++;continue;}Kind k=b[r][c].k;int e=r+1;while(e<R&&b[e][c]!=null&&b[e][c].k==k)e++;int len=e-r;if(len>=3){m.runs++;m.lens.add(len);for(int y=r;y<e;y++)m.cells.add(y*C+c);}r=e;}}return m;}
 void swap(int a,int d,int z,int q){Tile t=b[a][d];b[a][d]=b[z][q];b[z][q]=t;} void anim(long dur,F f,Runnable end){ValueAnimator a=ValueAnimator.ofFloat(0,1);a.setDuration(dur);a.setInterpolator(new DecelerateInterpolator());a.addUpdateListener(v->f.u((Float)v.getAnimatedValue()));a.addListener(new AnimatorListenerAdapter(){public void onAnimationEnd(Animator x){end.run();}});a.start();}interface F{void u(float v);}float lerp(float a,float b,float t){return a+(b-a)*t;}
 void center(Canvas c,String s,float y,float size,int color){tx.setTextSize(Math.max(12,size));tx.setColor(color);tx.setTextAlign(Paint.Align.CENTER);c.drawText(s,w/2,y,tx);}void button(Canvas c,RectF r,String s){p.setColor(0xffea580c);c.drawRoundRect(r,25,25,p);centerAt(c,s,r.centerX(),r.centerY()+w*.015f,w*.044f,Color.WHITE);}void centerAt(Canvas c,String s,float x,float y,float size,int color){tx.setTextSize(size);tx.setColor(color);tx.setTextAlign(Paint.Align.CENTER);c.drawText(s,x,y,tx);}
 protected void onDetachedFromWindow(){super.onDetachedFromWindow();if(sounds!=null)sounds.release();}
}
