from pathlib import Path
p=Path('app/src/main/java/com/brokengeargaming/torquematch/TorqueMatchView.java')
s=p.read_text()

def rep(old,new):
    global s
    if old not in s:
        raise SystemExit('Missing patch target: '+old[:120])
    s=s.replace(old,new,1)

rep('Tile[][] b=new Tile[R][C]; RectF start=new RectF(),next=new RectF(); RectF[] boostBtns={new RectF(),new RectF(),new RectF(),new RectF()};',
'''Tile[][] b=new Tile[R][C]; boolean[][] shape=new boolean[R][C]; int[][] barrier=new int[R][C]; RectF start=new RectF(),next=new RectF(); RectF[] boostBtns={new RectF(),new RectF(),new RectF(),new RectF()};''')
rep('int bombCount,wrenchCount,nitroCount,movesCount; String awardText=""; Booster armed=Booster.NONE; boolean nitroVertical=false;',
'''int bombCount,wrenchCount,nitroCount,movesCount; String awardText=""; Booster armed=Booster.NONE; boolean nitroVertical=false; int challengeType,objectiveGoal,objectiveDone,barrierTotal; Kind objectiveKind=null; String challengeName="";''')
rep('enum Kind{WHEEL,ROTOR,TURBO,SPARK,GEAR,PISTON}', 'enum Kind{WHEEL,ROTOR,TURBO,SPARK,GEAR,PISTON,NUT,SCREW}')

rep('void game(Canvas c){center(c,"LEVEL "+level,hh*.048f,w*.046f,Color.WHITE);center(c,"SCORE "+score+" / "+target,hh*.09f,w*.039f,0xffff7316);center(c,"MOVES  "+moves,hh*.13f,w*.040f,moves<=5?0xffef4444:Color.LTGRAY);if(!banner.isEmpty()&&System.currentTimeMillis()<bannerUntil){center(c,banner,hh*.177f,w*.037f,0xffffcc15);postInvalidateOnAnimation();}\n        RectF tray=new RectF(left-8,top-8,left+cell*C+8,top+cell*R+8);p.setColor(0xff16161a);c.drawRoundRect(tray,22,22,p);\n        for(int r=0;r<R;r++)for(int col=0;col<C;col++){Tile t=b[r][col];if(t==null)continue;float rr=r,cc=col;if(swapAnim){if(r==r1&&col==c1){rr=lerp(r1,r2,sp);cc=lerp(c1,c2,sp);}else if(r==r2&&col==c2){rr=lerp(r2,r1,sp);cc=lerp(c2,c1,sp);}}else if(fp<1&&fall.containsKey(t.id))rr=lerp(fall.get(t.id),r,fp);tile(c,rr,cc,t,clearing.contains(r*C+col)?1-cp:1);}',
'''void game(Canvas c){center(c,"LEVEL "+level,hh*.044f,w*.043f,Color.WHITE);center(c,"SCORE "+score+" / "+target,hh*.082f,w*.035f,0xffff7316);center(c,"MOVES  "+moves,hh*.118f,w*.036f,moves<=5?0xffef4444:Color.LTGRAY);center(c,challengeName,hh*.154f,w*.030f,0xffffcc15);String obj=objectiveText();if(!obj.isEmpty())center(c,obj,hh*.184f,w*.027f,0xffa3e635);if(!banner.isEmpty()&&System.currentTimeMillis()<bannerUntil){center(c,banner,hh*.212f,w*.030f,0xffffcc15);postInvalidateOnAnimation();}\n        if(challengeType!=1){RectF tray=new RectF(left-8,top-8,left+cell*C+8,top+cell*R+8);p.setColor(0xff16161a);c.drawRoundRect(tray,22,22,p);}\n        for(int r=0;r<R;r++)for(int col=0;col<C;col++){if(barrier[r][col]>0){drawBarrier(c,r,col,barrier[r][col]);continue;}Tile t=b[r][col];if(t==null)continue;float rr=r,cc=col;if(swapAnim){if(r==r1&&col==c1){rr=lerp(r1,r2,sp);cc=lerp(c1,c2,sp);}else if(r==r2&&col==c2){rr=lerp(r2,r1,sp);cc=lerp(c2,c1,sp);}}else if(fp<1&&fall.containsKey(t.id))rr=lerp(fall.get(t.id),r,fp);tile(c,rr,cc,t,clearing.contains(r*C+col)?1-cp:1);}''')

rep('case PISTON:p.setColor(0xffa3e635);c.drawRoundRect(new RectF(cx-s*.55f,cy-s*.65f,cx+s*.55f,cy-s*.05f),8,8,p);p.setStrokeWidth(s*.18f);c.drawLine(cx,cy,cx,cy+s*.7f,p);break;}',
'''case PISTON:p.setColor(0xffa3e635);c.drawRoundRect(new RectF(cx-s*.55f,cy-s*.65f,cx+s*.55f,cy-s*.05f),8,8,p);p.setStrokeWidth(s*.18f);c.drawLine(cx,cy,cx,cy+s*.7f,p);break;case NUT:p.setColor(0xffd6d3d1);Path np=new Path();for(int i=0;i<6;i++){double a=Math.PI/3*i-Math.PI/6;float px=cx+(float)Math.cos(a)*s*.8f,py=cy+(float)Math.sin(a)*s*.8f;if(i==0)np.moveTo(px,py);else np.lineTo(px,py);}np.close();c.drawPath(np,p);p.setColor(0xff27272a);c.drawCircle(cx,cy,s*.32f,p);break;case SCREW:p.setColor(0xff94a3b8);c.drawRoundRect(new RectF(cx-s*.42f,cy-s*.7f,cx+s*.42f,cy-s*.18f),8,8,p);p.setStrokeWidth(s*.17f);c.drawLine(cx-s*.25f,cy-s*.44f,cx+s*.25f,cy-s*.44f,p);c.drawRect(cx-s*.10f,cy-s*.18f,cx+s*.10f,cy+s*.72f,p);break;}''')

rep('void begin(){h.removeCallbacksAndMessages(null);state=State.PLAYING;score=0;moves=Math.max(16,24-(level-1)/3);startMoves=moves;target=2800+(level-1)*950;locked=false;armed=Booster.NONE;clearing.clear();fall.clear();fp=1;banner="";awardText="";fill();invalidate();}',
'''void begin(){h.removeCallbacksAndMessages(null);state=State.PLAYING;score=0;moves=Math.max(16,24-(level-1)/3);startMoves=moves;target=2800+(level-1)*950;locked=false;armed=Booster.NONE;clearing.clear();fall.clear();fp=1;banner="";awardText="";setupChallenge();fill();invalidate();}''')
rep('void fill(){for(int r=0;r<R;r++)for(int c=0;c<C;c++){Kind k;do{k=Kind.values()[rnd.nextInt(6)];}while((c>=2&&b[r][c-1].k==k&&b[r][c-2].k==k)||(r>=2&&b[r-1][c].k==k&&b[r-2][c].k==k));b[r][c]=new Tile(k);}}',
'''void fill(){for(int r=0;r<R;r++)for(int c=0;c<C;c++){b[r][c]=null;if(!playable(r,c))continue;Kind k;do{k=randomKind();}while((c>=2&&playable(r,c-1)&&playable(r,c-2)&&b[r][c-1]!=null&&b[r][c-2]!=null&&b[r][c-1].k==k&&b[r][c-2].k==k)||(r>=2&&playable(r-1,c)&&playable(r-2,c)&&b[r-1][c]!=null&&b[r-2][c]!=null&&b[r-1][c].k==k&&b[r-2][c].k==k));b[r][c]=new Tile(k);}}''')

rep('if(rr>=0&&rr<R&&cc>=0&&cc<C){useArmed(rr,cc);dr=dc=-1;return true;}', 'if(rr>=0&&rr<R&&cc>=0&&cc<C&&playable(rr,cc)){useArmed(rr,cc);dr=dc=-1;return true;}')
rep('if(dr<0||dr>=R||dc<0||dc>=C)dr=dc=-1;', 'if(dr<0||dr>=R||dc<0||dc>=C||!playable(dr,dc))dr=dc=-1;')
rep('if(nr>=0&&nr<R&&nc>=0&&nc<C){used=true;doSwap(dr,dc,nr,nc);}', 'if(nr>=0&&nr<R&&nc>=0&&nc<C&&playable(nr,nc)){used=true;doSwap(dr,dc,nr,nc);}')

rep('void clearAnimate(Set<Integer> ex,Runnable after){locked=true;clearing.clear();clearing.addAll(ex);cp=0;anim(CL,v->{cp=v;invalidate();},()->{for(int pos:ex)b[pos/C][pos%C]=null;clearing.clear();gravity();anim(FA,v->{fp=v;invalidate();},()->{fp=1;fall.clear();h.postDelayed(after,PA);});});}',
'''void clearAnimate(Set<Integer> ex,Runnable after){locked=true;clearing.clear();clearing.addAll(ex);cp=0;anim(CL,v->{cp=v;invalidate();},()->{countObjectives(ex);hitBarriers(ex);for(int pos:ex)if(pos>=0&&pos<R*C)b[pos/C][pos%C]=null;clearing.clear();gravity();anim(FA,v->{fp=v;invalidate();},()->{fp=1;fall.clear();h.postDelayed(after,PA);});});}''')

rep('void finish(){locked=false;if(score>=target){stars=calcStars();reward=calcReward();totalCredits+=reward;awardBoosters();pref.edit().putInt("credits",totalCredits).apply();saveBoosters();sfx(9,1);state=State.COMPLETE_ANIM;celebrateAt=System.currentTimeMillis();invalidate();h.postDelayed(()->{state=State.COMPLETE;invalidate();},1400);}else if(moves<=0){state=State.FAILED;invalidate();}}',
'''void finish(){locked=false;if(score>=target&&objectiveComplete()){stars=calcStars();reward=calcReward();totalCredits+=reward;awardBoosters();pref.edit().putInt("credits",totalCredits).apply();saveBoosters();sfx(9,1);state=State.COMPLETE_ANIM;celebrateAt=System.currentTimeMillis();invalidate();h.postDelayed(()->{state=State.COMPLETE;invalidate();},1400);}else if(moves<=0){state=State.FAILED;invalidate();}}''')

rep('void gravity(){fall.clear();for(int c=0;c<C;c++){int wr=R-1;for(int r=R-1;r>=0;r--)if(b[r][c]!=null){Tile t=b[r][c];if(wr!=r){b[wr][c]=t;b[r][c]=null;fall.put(t.id,(float)r);}wr--;}int si=0;while(wr>=0){Tile t=new Tile(Kind.values()[rnd.nextInt(6)]);b[wr][c]=t;fall.put(t.id,-1f-si++);wr--;}}fp=0;}',
'''void gravity(){fall.clear();for(int c=0;c<C;c++){int bottom=R-1;while(bottom>=0){while(bottom>=0&&!playable(bottom,c))bottom--;if(bottom<0)break;int topSeg=bottom;while(topSeg-1>=0&&playable(topSeg-1,c))topSeg--;int wr=bottom;for(int r=bottom;r>=topSeg;r--)if(b[r][c]!=null){Tile t=b[r][c];if(wr!=r){b[wr][c]=t;b[r][c]=null;fall.put(t.id,(float)r);}wr--;}int si=0;while(wr>=topSeg){Tile t=new Tile(randomKind());b[wr][c]=t;fall.put(t.id,(float)(topSeg-1-si++));wr--;}bottom=topSeg-1;}}fp=0;}''')

insert='''\n    boolean playable(int r,int c){return r>=0&&r<R&&c>=0&&c<C&&shape[r][c]&&barrier[r][c]<=0;}\n    Kind randomKind(){if(challengeType==3&&rnd.nextFloat()<.23f)return Kind.NUT;if(challengeType==4&&rnd.nextFloat()<.23f)return Kind.SCREW;return Kind.values()[rnd.nextInt(6)];}\n    void setupChallenge(){for(int r=0;r<R;r++)for(int c=0;c<C;c++){shape[r][c]=true;barrier[r][c]=0;b[r][c]=null;}challengeType=((level-1)/10)%5;int tier=(level-1)/50,within=(level-1)%10;objectiveKind=null;objectiveGoal=objectiveDone=barrierTotal=0;if(challengeType==0){challengeName="STANDARD GARAGE";}else if(challengeType==1){challengeName="DIAMOND BAY";for(int r=0;r<R;r++)for(int c=0;c<C;c++){double d=Math.abs(r-3.5)+Math.abs(c-3.5);shape[r][c]=d<=4.5;}}else if(challengeType==2){challengeName="BLOCKED SHOP FLOOR";int hp=within>=5?2:1;int[][] pts={{2,2},{2,5},{4,1},{4,6},{6,3},{6,4}};for(int[] q:pts){barrier[q[0]][q[1]]=hp;barrierTotal++;}objectiveGoal=barrierTotal;}else if(challengeType==3){challengeName="NUT HUNT";objectiveKind=Kind.NUT;objectiveGoal=10+within*2+tier*4;}else{challengeName="SCREW HUNT";objectiveKind=Kind.SCREW;objectiveGoal=10+within*2+tier*4;}}\n    String objectiveText(){if(challengeType==2)return "BREAK BARRIERS  "+objectiveDone+" / "+objectiveGoal;if(objectiveKind!=null)return "CLEAR "+objectiveKind+"S  "+objectiveDone+" / "+objectiveGoal;return "";}\n    boolean objectiveComplete(){return objectiveGoal<=0||objectiveDone>=objectiveGoal;}\n    void countObjectives(Set<Integer> ex){if(objectiveKind==null)return;for(int pos:ex)if(pos>=0&&pos<R*C){Tile t=b[pos/C][pos%C];if(t!=null&&t.k==objectiveKind)objectiveDone++;}}\n    void hitBarriers(Set<Integer> ex){if(challengeType!=2)return;Set<Integer> hit=new HashSet<>();for(int pos:ex){int r=pos/C,c=pos%C;int[][] d={{1,0},{-1,0},{0,1},{0,-1}};for(int[] z:d){int rr=r+z[0],cc=c+z[1];if(rr>=0&&rr<R&&cc>=0&&cc<C&&barrier[rr][cc]>0)hit.add(rr*C+cc);}}for(int pos:hit){int r=pos/C,c=pos%C;barrier[r][c]--;if(barrier[r][c]==0){objectiveDone++;flash("BARRIER BROKEN!  "+objectiveDone+" / "+objectiveGoal);}}}\n    void drawBarrier(Canvas c,int r,int col,int hp){float x=left+col*cell,y=top+r*cell;p.setColor(hp>1?0xff7c2d12:0xff9a3412);c.drawRoundRect(new RectF(x+4,y+4,x+cell-4,y+cell-4),cell*.12f,cell*.12f,p);p.setColor(0xffd6d3d1);p.setStrokeWidth(cell*.06f);for(int i=1;i<=2;i++){float yy=y+cell*i/3f;c.drawLine(x+cell*.18f,yy,x+cell*.82f,yy,p);}centerAt(c,hp>1?"2":"1",x+cell*.5f,y+cell*.58f,cell*.26f,Color.WHITE);}\n'''
rep('\n    void sfx(int type,float rate){', insert+'\n    void sfx(int type,float rate){')

p.write_text(s)
print('challenge patch applied')
